import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { lovelace, apparel, apparelDisplay } from "./fonts";
import { TransitionProvider } from "@/components/transition/TransitionProvider";
import { IntroGate } from "@/components/intro/IntroGate";
import { LocaleProvider } from "@/components/i18n/LocaleProvider";
import { LenisProvider } from "@/components/scroll/LenisProvider";
import { Header } from "@/components/layout/Header";
import { SiteBackground } from "@/components/layout/SiteBackground";
import { getInitialLocale } from "@/lib/i18n/get-locale";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getInitialLocale();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} ${lovelace.variable} ${apparel.variable} ${apparelDisplay.variable} min-h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SiteBackground />
        <LenisProvider>
          <LocaleProvider initialLocale={locale}>
            <TransitionProvider>
              <Header />
              <IntroGate>
                <main className="flex flex-1 flex-col">
                  {children}
                </main>
              </IntroGate>
            </TransitionProvider>
          </LocaleProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
