import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { lovelace } from "./fonts";
import { TransitionProvider } from "@/components/transition/TransitionProvider";
import { IntroGate } from "@/components/intro/IntroGate";
import { LocaleProvider } from "@/components/i18n/LocaleProvider";
import { LanguageSwitcher } from "@/components/i18n/LanguageSwitcher";
import { getInitialLocale } from "@/lib/i18n/get-locale";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getInitialLocale();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} ${lovelace.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LocaleProvider initialLocale={locale}>
          <TransitionProvider>
            <IntroGate>{children}</IntroGate>
          </TransitionProvider>
          <div className="fixed top-4 right-4 z-40">
            <LanguageSwitcher />
          </div>
        </LocaleProvider>
      </body>
    </html>
  );
}
